(function(){
  let data=null, market='Canada';
  const $=id=>document.getElementById(id), n=v=>{v=Number(v);return Number.isFinite(v)?v:null}, clamp=v=>Math.max(0,Math.min(100,v));
  function money(v,c){if(v==null||!isFinite(v))return '—';return new Intl.NumberFormat(c==='INR'?'en-IN':'en-CA',{style:'currency',currency:c==='INR'?'INR':'CAD',maximumFractionDigits:2}).format(v)}
  function pct(v){return v==null||!isFinite(v)?'—':(v*100).toFixed(1)+'%'} function num(v){return v==null||!isFinite(v)?'—':Number(v).toFixed(1)}
  function suitability(s){const x=((s.name||'')+' '+(s.industry||'')).toLowerCase();return /split corp|split share|closed-end|asset management/.test(x)?35:100}
  function score(s){const rg=n(s.revenueGrowth),eg=n(s.earningsGrowth),roe=n(s.roe),pm=n(s.profitMargin),de=n(s.debtToEquity),pe=n(s.pe),peg=n(s.peg),fcf=n(s.freeCashFlow),ocf=n(s.operatingCashFlow),t=s.technical||{},m3=n(t.momentum3M),m6=n(t.momentum6M);
    let growth=50;if(rg!=null)growth+=Math.max(-20,Math.min(25,rg*35));if(eg!=null)growth+=Math.max(-20,Math.min(25,eg*25));growth=clamp(growth);
    let quality=50;if(roe!=null)quality+=Math.max(-15,Math.min(20,roe*45));if(pm!=null)quality+=Math.max(-15,Math.min(15,pm*30));if(fcf!=null)quality+=fcf>0?8:-10;if(ocf!=null)quality+=ocf>0?7:-10;if(de!=null&&de>150)quality-=15;quality=clamp(quality);
    let valuation=50;if(pe!=null)valuation+=pe>0&&pe<=25?15:pe>50?-12:0;if(peg!=null)valuation+=peg>0&&peg<=1.5?12:peg>3?-8:0;valuation=clamp(valuation);
    let momentum=50;if(m3!=null)momentum+=Math.max(-20,Math.min(20,m3*50));if(m6!=null)momentum+=Math.max(-20,Math.min(20,m6*35));if(m6!=null&&m6>1)momentum-=15;momentum=clamp(momentum);
    const fields=[rg,eg,roe,pm,de,pe,fcf,ocf,m3,m6],confidence=Math.round(fields.filter(x=>x!=null).length/fields.length*100),fit=suitability(s);
    let total=growth*.30+quality*.30+valuation*.15+momentum*.10+confidence*.10+fit*.05;if(fit<50)total=Math.min(total,59);if(confidence<50)total=Math.min(total,64);
    return {total:Math.round(clamp(total)*10)/10,growth:Math.round(growth),quality:Math.round(quality),valuation:Math.round(valuation),momentum:Math.round(momentum),confidence,fit};
  }
  function verdict(s){if(s>=80)return 'High Conviction Screen';if(s>=70)return 'Strong Candidate';if(s>=60)return 'Promising';return 'High Risk / Review'}
  function render(){const m=data.markets[market],cur=market==='India'?'INR':'CAD',rows=m.stocks.map(s=>({...s,_v2:score(s)})).sort((a,b)=>b._v2.total-a._v2.total);m._rows=rows;$('title').textContent=market+' Small Cap / Sky Rocket Radar';$('subtitle').textContent='Higher-risk growth screen with business-quality, valuation, cash-flow, data-confidence and momentum checks. Structured investment vehicles are penalized because their ratios are not comparable to operating companies.';$('count').textContent=rows.length;$('cards').innerHTML=rows.map((s,i)=>`<article class="card" onclick="show(${i})"><div class="rank">#${i+1}</div><div class="main"><h2>${s.name||s.ticker}</h2><div class="ticker">${s.ticker} · ${s.sector||'Unknown'} · ${s.industry||'Unknown'}</div><div class="tags"><span>${verdict(s._v2.total)}</span><span>V2 ${num(s._v2.total)}</span><span>Data ${s._v2.confidence}%</span></div></div><div class="price">${money(s.price,cur)}</div></article>`).join('')}
  window.show=function(i){const s=data.markets[market]._rows[i],cur=market==='India'?'INR':'CAD',v=s._v2;$('cards').style.display='none';$('detail').style.display='block';$('detail').innerHTML=`<button class="back" onclick="back()">← Back to Small Cap Radar</button><section class="detail"><div class="eyebrow">${market} · ${s.sector||'Unknown'} · ${s.industry||'Unknown'}</div><h1>${s.name}</h1><div class="ticker">${s.ticker}</div><div class="score">${num(v.total)} <span>${verdict(v.total)}</span></div><div class="grid">${metric('Growth',v.growth+'/100')}${metric('Quality',v.quality+'/100')}${metric('Valuation',v.valuation+'/100')}${metric('Momentum',v.momentum+'/100')}${metric('Data Confidence',v.confidence+'%')}${metric('Business Fit',v.fit+'/100')}${metric('Price',money(s.price,cur))}${metric('Market Cap',money(s.marketCap,cur))}${metric('Revenue Growth',pct(s.revenueGrowth))}${metric('Earnings Growth',pct(s.earningsGrowth))}${metric('ROE',pct(s.roe))}${metric('Margin',pct(s.profitMargin))}${metric('P/E',num(s.pe))}${metric('Debt/Equity',num(s.debtToEquity))}</div><div class="thesis"><h3>Why it ranks here</h3><p>The V2 score emphasizes durable growth and business quality, then checks valuation, market confirmation and data coverage. Positive cash flow helps quality; extreme leverage, incomplete data and momentum excess reduce confidence.</p>${v.fit<50?'<p class="warning">Business-type warning: this appears to be an investment/structured vehicle rather than a conventional operating growth company, so its score is capped.</p>':''}<p class="warning">Small caps can lose a large portion of their value. This is a research screen, not a prediction of future returns.</p></div></section>`}
  function metric(a,b){return `<div class="metric"><small>${a}</small><strong>${b}</strong></div>`}
  window.back=function(){$('detail').style.display='none';$('cards').style.display='block'};window.setMarket=function(m){market=m;document.querySelectorAll('.market').forEach(b=>b.classList.toggle('active',b.dataset.market===m));render();back()};
  fetch('data/smallcap_universe.json?'+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('No small-cap data yet');return r.json()}).then(d=>{data=d;render()}).catch(e=>{$('cards').innerHTML='<div class="empty">Small-cap data could not be loaded. Please refresh.</div>'})
})();