(function(){
  let data=null, market='Canada';
  const $=id=>document.getElementById(id);
  function money(v,c){if(v==null||!isFinite(v))return '—';return new Intl.NumberFormat(c==='INR'?'en-IN':'en-CA',{style:'currency',currency:c==='INR'?'INR':'CAD',maximumFractionDigits:2}).format(v)}
  function pct(v){return v==null||!isFinite(v)?'—':(v*100).toFixed(1)+'%'}
  function num(v){return v==null||!isFinite(v)?'—':Number(v).toFixed(2)}
  function verdict(s){if(s>=80)return ['Rocket Candidate','green'];if(s>=70)return ['High Potential','green'];if(s>=60)return ['Promising','yellow'];return ['Speculative','red']}
  function render(){const m=data.markets[market],cur=market==='India'?'INR':'CAD';$('title').textContent=market+' Small Cap / Sky Rocket Radar';$('subtitle').textContent='10 small-cap companies selected for asymmetric long-term upside. Growth first, but filtered for quality, valuation, balance-sheet risk and market confirmation.';$('count').textContent=m.selected_count;$('cards').innerHTML=m.stocks.map((s,i)=>{const v=verdict(s.universeScore);return `<article class="card" onclick="show(${i})"><div class="rank">#${i+1}</div><div class="main"><h2>${s.name||s.ticker}</h2><div class="ticker">${s.ticker} · ${s.sector||'Unknown'} · ${s.industry||'Unknown'}</div><div class="tags"><span>${v[0]}</span><span>Score ${num(s.universeScore)}</span></div></div><div class="price">${money(s.price,cur)}</div></article>`}).join('')}
  window.show=function(i){const s=data.markets[market].stocks[i],cur=market==='India'?'INR':'CAD';$('cards').style.display='none';$('detail').style.display='block';const v=verdict(s.universeScore);$('detail').innerHTML=`<button class="back" onclick="back()">← Back to Small Cap Radar</button><section class="detail"><div class="eyebrow">${market} · ${s.sector||'Unknown'} · ${s.industry||'Unknown'}</div><h1>${s.name}</h1><div class="ticker">${s.ticker}</div><div class="score">${num(s.universeScore)} <span>${v[0]}</span></div><div class="grid">${metric('Price',money(s.price,cur))}${metric('Market Cap',money(s.marketCap,cur))}${metric('Revenue Growth',pct(s.revenueGrowth))}${metric('Earnings Growth',pct(s.earningsGrowth))}${metric('ROE',pct(s.roe))}${metric('Margin',pct(s.profitMargin))}${metric('P/E',num(s.pe))}${metric('Forward P/E',num(s.forwardPE))}${metric('PEG',num(s.peg))}${metric('P/B',num(s.priceToBook))}${metric('Debt/Equity',num(s.debtToEquity))}${metric('Beta',num(s.beta))}${metric('Insider',pct(s.insiderOwnership))}${metric('Institutional',pct(s.institutionalOwnership))}</div><div class="thesis"><h3>Why it made the Sky Rocket list</h3><p>${s.thesis}</p><ul><li><b>Growth:</b> ${s.screening.growth}</li><li><b>Quality:</b> ${s.screening.quality}</li><li><b>Valuation:</b> ${s.screening.valuation}</li><li><b>Momentum:</b> ${s.screening.momentum}</li><li><b>Risk control:</b> ${s.screening.risk}</li></ul><p class="warning">Small-cap stocks can lose a large portion of their value. This is a high-risk opportunity list, not a guarantee of a future “rocket”.</p></div></section>`}
  function metric(a,b){return `<div class="metric"><small>${a}</small><strong>${b}</strong></div>`}
  window.back=function(){$('detail').style.display='none';$('cards').style.display='block'};
  window.setMarket=function(m){market=m;document.querySelectorAll('.market').forEach(b=>b.classList.toggle('active',b.dataset.market===m));render();back()};
  fetch('data/smallcap_universe.json').then(r=>{if(!r.ok)throw Error('No small-cap data yet');return r.json()}).then(d=>{data=d;render()}).catch(e=>{$('cards').innerHTML='<div class="empty">Small-cap data is being built. Refresh after the next universe run.</div>'})
})();
